### ISSUE TITLE
Add Friend Validation

### ISSUE THREAD

**Issue by Cristo12345** [ChibiKev/Split-It#129]
On 'Friends' page users can add users that have already sent them a request. 

Ex.
1. Person B sends Person A a friend request
2. A sends B a friend request
3. There are now two entries in Friendship table for the same friendship

**Comment by ChibiKev** [comment]
There is one way you could approach this. 
For
2. A sends B a friend request
Let A check to see if B is in the pending friend request, if not, send the request. If so, do not allow them to send the request and state that the friend is pending.

**Comment by Cristo12345** [comment]
Yeah I was thinking the same.

**Comment by Cristo12345** [comment]
Just checked to see if Friendship exists before sending a Friend request. Tested with Kevin.
