### ISSUE TITLE
In-app Currency Simulation

### ISSUE THREAD

**Issue by ChibiKev** [ChibiKev/Split-It#26]
- Adding “dummy money” to users’ account

**Comment by Cristo12345** [comment]
Users now have a balance associated with their account. This balance is 9 digits with 2 being decimals. No functionality (transfer, adding, removing) to this column yet.

**Comment by ChibiKev** [comment]
so it would something like xxxxxxx.xx?
and the max would be 9999999.99, correct?

**Comment by Cristo12345** [comment]
I believe so as it should behave similar to FLOAT. We can play with this later on when we are able to add money to a User's balance

**Comment by Cristo12345** [comment]
Still need to add functionalities for adding, transferring, etc money between users and transactions but all users have $0.00 when creating an account so im marking this as complete for this month
